export enum AUTH_ACTION_TYPES {
  SIGN_UP = '[POST] SIGN UP USER',
  AUTH_CHECKED = '[GET] AUTH CHECKED',
  USER_CHECKED = 'USER_CHECKED',
  LOGIN = '[POST] LOGIN USER',
  USER_LOGGED = 'USER_LOGGED',
  CHECK_AUTH = '[GET] CHECK AUTH',
  SET_LOGIN_ERROR = 'SET_LOGIN_ERROR',
}
